site_name: Hands - Testing Tools
site_url: https://hands-testing-tools.example
site_author: Andreas Felix Häberle
site_description: Comprehensive overview of testing tools and methodologies

# Repository
repo_name: 42sol-eu/hands
repo_url: https://github.com/42sol-eu/hands
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Andreas Felix Häberle

# Configuration
theme:
  name: material
  language: en
  
  # Palette configuration
  palette:
    # Dark Mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: deep purple

    # light Mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: deep orange
  
  # Features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  
  # Icons
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    
  # Font
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: 42sol-eu
      repo: hands
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Goals: goals.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Testing Tools:
    - Overview: tools/overview.md
    - Unit Testing: tools/unit-testing.md
    - Integration Testing: tools/integration-testing.md
    - End-to-End Testing: tools/e2e-testing.md
  - Best Practices:
    - Testing Strategy: best-practices/strategy.md
    - Code Quality: best-practices/code-quality.md
  - Reference:
    - API: reference/api.md
    - Configuration: reference/configuration.md
  - Contributing: contributing.md

# Additional Configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/42sol-eu
      name: GitHub
  version:
    provider: mike
    default: stable

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js